workflows:
  dvr-timer-ios-testflight-workflow:
    name: DVR Timer iOS Build and Publish to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      # نفس الـ integration المربوط بحسابك
      app_store_connect: noourway

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      ios_signing:
        provisioning_profiles:
          - dvr_timer_Manual_Profile # اسم البروفايل الجديد الخاص بالتطبيق
        certificates:
          - ios_cert_manual # نفس شهادة المطور المعتمدة

    scripts:
      - name: Set iOS deployment target
        script: |
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Clean and Get Dependencies
        script: |
          flutter clean
          flutter pub upgrade
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod repo update
          pod install

      - name: Apply Vault Profiles
        script: xcode-project use-profiles

      - name: Setup Apple Sign In Entitlements
        script: |
          # إنشاء ملف الصلاحيات الخاص بأبل
          cat <<EOF > ios/Runner/Runner.entitlements
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.developer.applesignin</key>
              <array>
                  <string>Default</string>
              </array>
          </dict>
          </plist>
          EOF
          # ربط الملف ببيئة العمل في إكس كود
          sed -i '' 's/INFOPLIST_FILE = Runner\/Info.plist;/INFOPLIST_FILE = Runner\/Info.plist; CODE_SIGN_ENTITLEMENTS = Runner\/Runner.entitlements;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - codexus.eg@gmail.com
