// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCutQWih9HnceffgvnHlBXofi4QQuVPs',
    appId: '1:211339829221:android:a5f0d62523d6eb280c590c',
    messagingSenderId: '211339829221',
    projectId: 'dvr-timer',
    storageBucket: 'dvr-timer.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVR1Y7SDeDn1rHrgq5vHPruSQFwZ4RiCo',
    appId: '1:211339829221:ios:ca3b3735581914090c590c',
    messagingSenderId: '211339829221',
    projectId: 'dvr-timer',
    storageBucket: 'dvr-timer.firebasestorage.app',
    androidClientId: '211339829221-0jnq5rq80i74cp4rcgm6euk2i33oagv0.apps.googleusercontent.com',
    iosClientId: '211339829221-mfhee0p31n7sr04ufktnmd0q66t68qcq.apps.googleusercontent.com',
    iosBundleId: 'com.dvrtime.codexus',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1dcr-CflG7jOu67E_4axbhWGyjNkvxEc',
    appId: '1:211339829221:web:f910699ee2ca266c0c590c',
    messagingSenderId: '211339829221',
    projectId: 'dvr-timer',
    authDomain: 'dvr-timer.firebaseapp.com',
    storageBucket: 'dvr-timer.firebasestorage.app',
    measurementId: 'G-QR6CEFEHYR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVR1Y7SDeDn1rHrgq5vHPruSQFwZ4RiCo',
    appId: '1:211339829221:ios:c020db51e8f233080c590c',
    messagingSenderId: '211339829221',
    projectId: 'dvr-timer',
    storageBucket: 'dvr-timer.firebasestorage.app',
    androidClientId: '211339829221-0jnq5rq80i74cp4rcgm6euk2i33oagv0.apps.googleusercontent.com',
    iosClientId: '211339829221-lnt9c3i871fqfavkl1uverq53unrgaov.apps.googleusercontent.com',
    iosBundleId: 'com.codexus.dvrTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1dcr-CflG7jOu67E_4axbhWGyjNkvxEc',
    appId: '1:211339829221:web:a360d1b9ae0d83370c590c',
    messagingSenderId: '211339829221',
    projectId: 'dvr-timer',
    authDomain: 'dvr-timer.firebaseapp.com',
    storageBucket: 'dvr-timer.firebasestorage.app',
    measurementId: 'G-CCTCNE69GC',
  );
}
